apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: crew-ai-test25092501
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/crew-ai-test25092501:5edc5169a3f10b98dab9f99ad30106fc73249725@sha256:d5c41dd1147d63bfcdd0b7fd85f033c79125b2a68220173aa7257bccf0969e1a # use pre-built to bootstrap
          name: app-inference
